import { StyleSheet } from "react-native";

import { colors, minimumTouchTarget, radius, spacing, typeScale } from "../../theme/tokens";

export const catalogStyles = StyleSheet.create({
  search: {
    minHeight: 48,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.lg,
    color: colors.ink,
    fontSize: typeScale.body,
  },
  categoryScroller: { flexGrow: 0, flexShrink: 0 },
  categoryList: {
    gap: spacing.sm,
    paddingVertical: spacing.lg,
    alignItems: "center",
  },
  category: {
    minHeight: minimumTouchTarget,
    justifyContent: "center",
    backgroundColor: colors.surface,
    borderRadius: radius.pill,
    paddingHorizontal: spacing.lg,
  },
  selectedCategory: { backgroundColor: colors.espresso },
  categoryText: { color: colors.muted, fontSize: 12, fontWeight: "600" },
  selectedCategoryText: { color: colors.surface },
  sectionTitleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: spacing.md,
  },
  itemCount: { color: colors.muted, fontSize: 12 },
  productsScroll: { flex: 1 },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: spacing.md,
    paddingBottom: 120,
  },
  product: {
    minWidth: 0,
    padding: spacing.sm,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.line,
  },
  productArt: {
    height: 90,
    borderRadius: radius.sm,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  symbol: { fontSize: 38, color: colors.espresso },
  categoryTag: {
    position: "absolute",
    top: 7,
    left: 7,
    color: colors.espresso,
    fontSize: 9,
    fontWeight: "700",
    backgroundColor: "#FFFFFFCC",
    paddingHorizontal: 7,
    paddingVertical: 4,
    borderRadius: radius.pill,
  },
  productName: {
    color: colors.ink,
    fontSize: 12,
    fontWeight: "700",
    marginTop: spacing.sm,
  },
  productDetail: { color: colors.muted, fontSize: 10, marginTop: 3 },
  priceRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: spacing.xs,
  },
  price: { color: colors.espresso, fontSize: 13, fontWeight: "800" },
  addButton: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.accentSoft,
    borderRadius: 10,
    width: minimumTouchTarget,
    height: minimumTouchTarget,
  },
  addButtonText: { color: colors.accent, fontSize: 22, fontWeight: "500" },
  empty: { color: colors.muted, paddingVertical: spacing.xl },
});
