import { StyleSheet } from "react-native";

import { colors, radius, spacing, typeScale } from "../../theme/tokens";

export const shellStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  header: {
    minHeight: 72,
    paddingHorizontal: spacing.xl,
    borderBottomWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  phoneHeader: { minHeight: 64, paddingHorizontal: spacing.md },
  brandRow: { flexDirection: "row", alignItems: "center", gap: spacing.md },
  brandMark: {
    width: 38,
    height: 38,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.accent,
  },
  brandLetter: { color: colors.surface, fontSize: 23, fontWeight: "800" },
  brand: {
    color: colors.ink,
    fontSize: 18,
    fontWeight: "800",
    letterSpacing: -0.4,
  },
  store: { color: colors.muted, fontSize: 9, letterSpacing: 1.1, marginTop: 2 },
  staff: {
    minHeight: 36,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    paddingHorizontal: spacing.md,
    borderRadius: radius.pill,
    backgroundColor: colors.background,
  },
  onlineDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: colors.success,
  },
  staffText: { color: colors.ink, fontSize: 12, fontWeight: "600" },
  workspace: { flex: 1 },
  tabletWorkspace: {
    flexDirection: "row",
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.xl,
    gap: spacing.xl,
  },
  catalogPane: {
    flex: 1,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xl,
  },
  headingRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: spacing.lg,
  },
  eyebrow: {
    color: colors.muted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1.2,
  },
  heading: {
    color: colors.ink,
    fontSize: typeScale.title,
    fontWeight: "800",
    letterSpacing: -0.5,
    marginTop: 5,
  },
  shift: { color: colors.success, fontSize: 12, fontWeight: "600" },
  sectionTitle: { color: colors.ink, fontSize: 17, fontWeight: "800" },
  mobileOrderBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    minHeight: 78,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    backgroundColor: colors.surface,
    borderTopWidth: 1,
    borderColor: colors.line,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  mobileCount: { color: colors.muted, fontSize: 11 },
  mobileTotal: {
    color: colors.ink,
    fontSize: 17,
    fontWeight: "800",
    marginTop: 2,
  },
});
